# Generated by Django 5.2.9 on 2026-03-25 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения среди соседних', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exhibit.location', verbose_name='Родительская локация')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('video', models.FileField(blank=True, help_text='Видео с объяснением гида', null=True, upload_to='exhibits/videos/', verbose_name='Видео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='exhibits/thumbnails/', verbose_name='Превью')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='exhibit.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаты',
                'ordering': ['order', 'title'],
            },
        ),
    ]
