# Generated by Django 5.2.9 on 2026-03-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0002_hall_section_migrate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='video_en',
            field=models.FileField(blank=True, help_text='Видео экспонатов', null=True, upload_to='exhibits/videos/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='video_ru',
            field=models.FileField(blank=True, help_text='Видео экспонатов', null=True, upload_to='exhibits/videos/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='video_uz',
            field=models.FileField(blank=True, help_text='Видео экспонатов', null=True, upload_to='exhibits/videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='video',
            field=models.FileField(blank=True, help_text='Видео экспонатов', null=True, upload_to='exhibits/videos/', verbose_name='Видео'),
        ),
    ]
