# Generated by Django 5.2.9 on 2026-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0003_exhibit_video_en_exhibit_video_ru_exhibit_video_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, verbose_name='Длительность (минут)'),
        ),
    ]
