# Generated by Django 5.2.9 on 2026-03-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0004_section_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='break_duration_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Длительность перерыва после завершения этого раздела', verbose_name='Перерыв после раздела (минут)'),
        ),
    ]
