# Generated by Django 5.2.9 on 2026-03-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0011_section_transition_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/maps/', verbose_name='Карта перехода к след. разделу'),
        ),
    ]
