# Generated by Django 5.2.9 on 2026-04-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0012_alter_section_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='exhibits/audio/', verbose_name='Аудио'),
        ),
        migrations.CreateModel(
            name='ExhibitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhibits/images/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibit.exhibit', verbose_name='Экспонат')),
            ],
            options={
                'verbose_name': 'Фото экспоната',
                'verbose_name_plural': 'Фото экспонатов',
                'ordering': ['order', 'id'],
            },
        ),
    ]
