# Generated by Django 5.2.9 on 2026-04-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0013_exhibit_audio_exhibitimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='thumbnail',
        ),
    ]
