# Generated by Django 5.2.9 on 2026-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0014_remove_exhibit_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='audio_en',
            field=models.FileField(blank=True, null=True, upload_to='exhibits/audio/', verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='audio_ru',
            field=models.FileField(blank=True, null=True, upload_to='exhibits/audio/', verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='audio_uz',
            field=models.FileField(blank=True, null=True, upload_to='exhibits/audio/', verbose_name='Аудио'),
        ),
    ]
