# Generated by Django 5.2.9 on 2026-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0015_exhibit_audio_en_exhibit_audio_ru_exhibit_audio_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=600, help_text='Фолбэк. Если есть видео гида — берётся max(длительность видео) + 1', verbose_name='Длительность (секунд)'),
        ),
    ]
