# Generated by Django 5.2.9 on 2026-04-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0016_alter_section_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_immersion_room',
            field=models.BooleanField(default=False, verbose_name='Иммерсивная комната'),
        ),
        migrations.AddField(
            model_name='section',
            name='immersion_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sections/immersion/', verbose_name='Фото Иммерсивной комнаты'),
        ),
    ]
