# Generated by Django 5.2.9 on 2026-04-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicefilestate',
            new_name='device_devi_device__5b8e27_idx',
            old_name='device_devi_device__bb09c8_idx',
        ),
    ]
