# Generated by Django 5.2.9 on 2026-03-26 04:34

import users.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.manager.UserManager()),
            ],
        ),
    ]
