# Generated by Django 5.2.9 on 2026-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Уникальный номер на бейдже', unique=True, verbose_name='Номер')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='specialists/avatars/', verbose_name='Аватар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TourSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание подключений'), ('in_progress', 'Тур идёт'), ('finished', 'Завершён')], default='waiting', max_length=20, verbose_name='Статус')),
                ('tourist_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во туристов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сессия тура',
                'verbose_name_plural': 'Сессии туров',
                'ordering': ['-created_at'],
            },
        ),
    ]
