# Generated by Django 5.2.9 on 2026-03-25 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0001_initial'),
        ('specialist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursession',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text='Локация, которую специалист сейчас показывает', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='exhibit.location', verbose_name='Текущая локация'),
        ),
        migrations.AlterField(
            model_name='toursession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание подключений'), ('in_progress', 'Тур идёт'), ('on_break', 'Перерыв'), ('finished', 'Завершён')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
    ]
