# Generated by Django 5.2.9 on 2026-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0004_toursession_current_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursession',
            name='paused_remaining_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток при паузе (секунд)'),
        ),
        migrations.AddField(
            model_name='toursession',
            name='section_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало текущего раздела'),
        ),
    ]
