# Generated by Django 5.2.9 on 2026-03-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0005_toursession_paused_remaining_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursession',
            name='break_remaining_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток перерыва (секунд)'),
        ),
        migrations.AddField(
            model_name='toursession',
            name='is_technical_stop',
            field=models.BooleanField(default=False, verbose_name='Техническая остановка'),
        ),
    ]
