# Generated by Django 5.2.9 on 2026-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0007_toursession_hall_transition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toursession',
            name='is_technical_stop',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Техническая остановка'),
        ),
    ]
