# Generated by Django 5.2.9 on 2026-04-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0008_alter_toursession_is_technical_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursession',
            name='pre_stop_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Ожидание подключений'), ('in_progress', 'Тур идёт'), ('on_break', 'Перерыв'), ('section_transition', 'Переход между разделами'), ('hall_transition', 'Переход между залами'), ('finished', 'Завершён')], help_text='Запоминается при тех. остановке, чтобы вернуться в правильный статус', max_length=20, null=True, verbose_name='Статус до тех. остановки'),
        ),
    ]
