# Generated by Django 5.2.9 on 2026-03-24 12:27

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Общие правила', max_length=255, verbose_name='Заголовок')),
                ('number', models.PositiveIntegerField(help_text='Порядковый номер (1, 2, 3...)', verbose_name='Номер блока')),
                ('content', martor.models.MartorField(help_text='Поддерживает markdown-разметку:\n- Списки с точками\n**Жирный текст**\n*Курсив*\nОбычный текст', verbose_name='Содержимое (Markdown)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Блок правил',
                'verbose_name_plural': 'Блоки правил',
                'ordering': ['number'],
            },
        ),
    ]
