# Generated by Django 5.2.9 on 2026-03-24 12:35

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='content_en',
            field=martor.models.MartorField(help_text='Поддерживает markdown-разметку:\n- Списки с точками\n**Жирный текст**\n*Курсив*\nОбычный текст', null=True, verbose_name='Содержимое (Markdown)'),
        ),
        migrations.AddField(
            model_name='rule',
            name='content_ru',
            field=martor.models.MartorField(help_text='Поддерживает markdown-разметку:\n- Списки с точками\n**Жирный текст**\n*Курсив*\nОбычный текст', null=True, verbose_name='Содержимое (Markdown)'),
        ),
        migrations.AddField(
            model_name='rule',
            name='content_uz',
            field=martor.models.MartorField(help_text='Поддерживает markdown-разметку:\n- Списки с точками\n**Жирный текст**\n*Курсив*\nОбычный текст', null=True, verbose_name='Содержимое (Markdown)'),
        ),
        migrations.AddField(
            model_name='rule',
            name='title_en',
            field=models.CharField(help_text='Например: Общие правила', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='rule',
            name='title_ru',
            field=models.CharField(help_text='Например: Общие правила', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='rule',
            name='title_uz',
            field=models.CharField(help_text='Например: Общие правила', max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
