# Generated by Django 5.2.9 on 2026-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_rename_description_guide_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_sign_language',
            field=models.BooleanField(default=False, help_text='Гид показывает жестами и говорит', verbose_name='Жестовый язык'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='subtitles',
            field=models.TextField(blank=True, default='', help_text='Текст субтитров для видео гида', verbose_name='Субтитры'),
        ),
    ]
