# Generated by Django 5.2.9 on 2026-03-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='guide',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='guide',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='guide',
            name='subtitles_en',
            field=models.TextField(blank=True, default='', help_text='Текст субтитров для видео гида', null=True, verbose_name='Субтитры'),
        ),
        migrations.AddField(
            model_name='guide',
            name='subtitles_ru',
            field=models.TextField(blank=True, default='', help_text='Текст субтитров для видео гида', null=True, verbose_name='Субтитры'),
        ),
        migrations.AddField(
            model_name='guide',
            name='subtitles_uz',
            field=models.TextField(blank=True, default='', help_text='Текст субтитров для видео гида', null=True, verbose_name='Субтитры'),
        ),
        migrations.AddField(
            model_name='guide',
            name='video_en',
            field=models.FileField(blank=True, null=True, upload_to='guides/videos/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='guide',
            name='video_ru',
            field=models.FileField(blank=True, null=True, upload_to='guides/videos/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='guide',
            name='video_uz',
            field=models.FileField(blank=True, null=True, upload_to='guides/videos/', verbose_name='Видео'),
        ),
    ]
