# Generated by Django 5.2.9 on 2026-03-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0005_section_break_duration_minutes'),
        ('guide', '0007_guide_name_en_guide_name_ru_guide_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='subtitles',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='subtitles_en',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='subtitles_ru',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='subtitles_uz',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='video',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='video_en',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='video_ru',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='video_uz',
        ),
        migrations.CreateModel(
            name='GuideVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='guides/videos/', verbose_name='Видео')),
                ('video_ru', models.FileField(null=True, upload_to='guides/videos/', verbose_name='Видео')),
                ('video_en', models.FileField(null=True, upload_to='guides/videos/', verbose_name='Видео')),
                ('video_uz', models.FileField(null=True, upload_to='guides/videos/', verbose_name='Видео')),
                ('subtitles', models.TextField(blank=True, default='', verbose_name='Субтитры')),
                ('subtitles_ru', models.TextField(blank=True, default='', null=True, verbose_name='Субтитры')),
                ('subtitles_en', models.TextField(blank=True, default='', null=True, verbose_name='Субтитры')),
                ('subtitles_uz', models.TextField(blank=True, default='', null=True, verbose_name='Субтитры')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок воспроизведения')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='guide.guide', verbose_name='Гид')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_videos', to='exhibit.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Видео гида',
                'verbose_name_plural': 'Видео гидов',
                'ordering': ['section', 'order'],
            },
        ),
    ]
