# Generated by Django 5.2.9 on 2026-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_remove_guide_subtitles_remove_guide_subtitles_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='guides/videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='guidevideo',
            name='video_en',
            field=models.FileField(blank=True, null=True, upload_to='guides/videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='guidevideo',
            name='video_ru',
            field=models.FileField(blank=True, null=True, upload_to='guides/videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='guidevideo',
            name='video_uz',
            field=models.FileField(blank=True, null=True, upload_to='guides/videos/', verbose_name='Видео'),
        ),
    ]
