# Generated by Django 5.2.9 on 2026-04-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_alter_guidevideo_video_alter_guidevideo_video_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='preview_video',
            field=models.FileField(blank=True, help_text='Короткое видео, показывается в списке гидов при выборе', null=True, upload_to='guides/previews/', verbose_name='Превью-видео'),
        ),
        migrations.AddField(
            model_name='guide',
            name='preview_video_en',
            field=models.FileField(blank=True, help_text='Короткое видео, показывается в списке гидов при выборе', null=True, upload_to='guides/previews/', verbose_name='Превью-видео'),
        ),
        migrations.AddField(
            model_name='guide',
            name='preview_video_ru',
            field=models.FileField(blank=True, help_text='Короткое видео, показывается в списке гидов при выборе', null=True, upload_to='guides/previews/', verbose_name='Превью-видео'),
        ),
        migrations.AddField(
            model_name='guide',
            name='preview_video_uz',
            field=models.FileField(blank=True, help_text='Короткое видео, показывается в списке гидов при выборе', null=True, upload_to='guides/previews/', verbose_name='Превью-видео'),
        ),
    ]
