# Generated by Django 5.2.9 on 2026-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_guide_preview_video_guide_preview_video_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически считывается из видео при загрузке', verbose_name='Длительность (секунд)'),
        ),
    ]
