# Generated by Django 5.2.9 on 2026-04-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0016_alter_section_duration_seconds'),
        ('guide', '0011_guidevideo_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='exhibits_video',
            field=models.FileField(blank=True, help_text='Одно на гида — играет во время auto_break при показе экспонатов', null=True, upload_to='guides/exhibits/', verbose_name='Видео для экспонатов'),
        ),
        migrations.AddField(
            model_name='guide',
            name='exhibits_video_en',
            field=models.FileField(blank=True, help_text='Одно на гида — играет во время auto_break при показе экспонатов', null=True, upload_to='guides/exhibits/', verbose_name='Видео для экспонатов'),
        ),
        migrations.AddField(
            model_name='guide',
            name='exhibits_video_ru',
            field=models.FileField(blank=True, help_text='Одно на гида — играет во время auto_break при показе экспонатов', null=True, upload_to='guides/exhibits/', verbose_name='Видео для экспонатов'),
        ),
        migrations.AddField(
            model_name='guide',
            name='exhibits_video_uz',
            field=models.FileField(blank=True, help_text='Одно на гида — играет во время auto_break при показе экспонатов', null=True, upload_to='guides/exhibits/', verbose_name='Видео для экспонатов'),
        ),
        migrations.AddField(
            model_name='guidevideo',
            name='transition_video',
            field=models.FileField(blank=True, help_text='Играет при section_transition после этого раздела', null=True, upload_to='guides/transitions/', verbose_name='Видео перехода к след. разделу'),
        ),
        migrations.AddField(
            model_name='guidevideo',
            name='transition_video_en',
            field=models.FileField(blank=True, help_text='Играет при section_transition после этого раздела', null=True, upload_to='guides/transitions/', verbose_name='Видео перехода к след. разделу'),
        ),
        migrations.AddField(
            model_name='guidevideo',
            name='transition_video_ru',
            field=models.FileField(blank=True, help_text='Играет при section_transition после этого раздела', null=True, upload_to='guides/transitions/', verbose_name='Видео перехода к след. разделу'),
        ),
        migrations.AddField(
            model_name='guidevideo',
            name='transition_video_uz',
            field=models.FileField(blank=True, help_text='Играет при section_transition после этого раздела', null=True, upload_to='guides/transitions/', verbose_name='Видео перехода к след. разделу'),
        ),
        migrations.CreateModel(
            name='GuideHallVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='guides/hall_transitions/', verbose_name='Видео перехода')),
                ('video_ru', models.FileField(blank=True, null=True, upload_to='guides/hall_transitions/', verbose_name='Видео перехода')),
                ('video_en', models.FileField(blank=True, null=True, upload_to='guides/hall_transitions/', verbose_name='Видео перехода')),
                ('video_uz', models.FileField(blank=True, null=True, upload_to='guides/hall_transitions/', verbose_name='Видео перехода')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_videos', to='guide.guide', verbose_name='Гид')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_videos', to='exhibit.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Видео гида — переход между залами',
                'verbose_name_plural': 'Видео гидов — переходы между залами',
                'unique_together': {('guide', 'hall')},
            },
        ),
    ]
