services:
  backend:
    volumes:
      - .:/app
      - vscode-data:/root/.vscode-server
      - vscode-cache:/root/.cache
    command: sleep infinity
    ports:
      - "8000:8000"

volumes:
  vscode-data:
  vscode-cache:
