# Generated by Django 5.2.9 on 2026-03-25 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialist', '0005_toursession_paused_remaining_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен устройства')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Присоединился')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Покинул')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_sessions', to='specialist.toursession', verbose_name='Сессия тура')),
            ],
            options={
                'verbose_name': 'Сессия туриста',
                'verbose_name_plural': 'Сессии туристов',
                'ordering': ['-created_at'],
            },
        ),
    ]
