# Generated by Django 5.2.9 on 2026-03-28 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_remove_guide_subtitles_remove_guide_subtitles_en_and_more'),
        ('tour', '0003_touristsession_device_name_touristsession_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristsession',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourist_sessions', to='guide.guide', verbose_name='Выбранный гид'),
        ),
    ]
