# Generated by Django 5.2.9 on 2026-04-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_touristsession_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='6-значный код для выхода из киоск-мода', verbose_name='PIN-код')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PIN киоска',
                'verbose_name_plural': 'PIN киоска',
            },
        ),
    ]
