# Generated by Django 5.2.9 on 2026-04-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_remove_guide_subtitles_remove_guide_subtitles_en_and_more'),
        ('specialist', '0009_toursession_pre_stop_status'),
        ('tour', '0005_kioskpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristsession',
            name='device_token',
            field=models.PositiveIntegerField(help_text='Число от 1 до 600', verbose_name='Номер устройства'),
        ),
        migrations.AddConstraint(
            model_name='touristsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device_token',), name='unique_active_device_token'),
        ),
    ]
