__all__ = (
    "ROSETTA_AUTO_UPLOAD",
    "ROSETTA_SHOW_AT_ADMIN_PANEL",
    "ROSETTA_MESSAGES_PER_PAGE",
)


ROSETTA_AUTO_UPLOAD = True
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_MESSAGES_PER_PAGE = 20
